# Generated by Django 3.1.2 on 2020-11-02 05:55

import app.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
#from django.utils.timezone import utc
from datetime import datetime, timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100, verbose_name='Employee Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email Id')),
                ('mobile', models.CharField(max_length=30, verbose_name='Mobile Num')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=30, verbose_name='Password')),
                ('dob', models.DateField()),
                ('doj', models.DateField()),
                ('bio_data', models.FileField(null=True, upload_to='documents/', verbose_name='Bio Data')),
                ('city', models.CharField(max_length=300, verbose_name=' City')),
                ('address', models.TextField(max_length=2000, verbose_name=' Address')),
                ('department', models.CharField(choices=[('', 'Select'), ('Knitting', 'Knitting'), ('Dying', 'Dying'), ('Cutting', 'Cutting and Stitching'), ('Printing', 'Printing'), ('Ironing', 'Ironing'), ('Quality', 'Quality Checking and Packing'), ('Checking', 'Checking and Approval')], max_length=300, verbose_name='Department')),
                ('user_type', models.CharField(choices=[('', 'Select'), ('Normal', 'Normal'), ('Manager', 'Manager')], max_length=300, verbose_name='User Type')),
            ],
        ),
        migrations.CreateModel(
            name='HRTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr_name', models.CharField(max_length=100, verbose_name='HR Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email Id')),
                ('mobile', models.CharField(max_length=30, verbose_name='Mobile Num')),
                ('username', models.CharField(max_length=30, verbose_name='Username')),
                ('password', models.CharField(max_length=30, verbose_name='Password')),
                ('dob', models.DateField()),
                ('doj', models.DateField()),
                ('bio_data', models.FileField(null=True, upload_to='documents/', verbose_name='Bio Data')),
                ('city', models.CharField(max_length=300, verbose_name=' City')),
                ('address', models.TextField(max_length=2000, verbose_name=' Address')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, default=app.models.increment_invoice_number, max_length=500, null=True, verbose_name='Order Id')),
                ('buyer_name', models.CharField(max_length=100, verbose_name='Buyer Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email Id')),
                ('mobile', models.CharField(max_length=30, verbose_name='Mobile Num')),
                ('order_item', models.CharField(max_length=300, verbose_name='Order Item')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('image', models.FileField(null=True, upload_to='product/', verbose_name='Product Sample Image')),
                ('ordered_date', models.DateField(verbose_name='Ordered Date')),
                ('delivery_date', models.DateField(verbose_name='Delivery Date')),
                ('amount_per_product', models.CharField(max_length=300, verbose_name='Amount Per Product')),
                ('city', models.CharField(max_length=300, verbose_name='Buyer City')),
                ('address', models.TextField(max_length=2000, verbose_name='Buyer Address')),
                ('notes', models.TextField(max_length=3000, verbose_name='Notes')),
                ('invoice_status', models.CharField(blank=True, default='NotSend', max_length=300, null=True, verbose_name='Invoice Status')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Work_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, verbose_name='Order Id')),
                ('material_name', models.CharField(max_length=300, null=True, verbose_name='Material Name')),
                ('total_quantity', models.CharField(max_length=30, verbose_name='Total Quantity')),
                ('final_delivered_Quantity', models.CharField(blank=True, max_length=30, null=True, verbose_name='Final Delivered Quantity')),
                ('delivery_date', models.DateField()),
                ('department', models.CharField(choices=[('', 'Select'), ('Knitting', 'Knitting'), ('Dying', 'Dying'), ('Cutting', 'Cutting and Stitching'), ('Printing', 'Printing'), ('Ironing', 'Ironing'), ('Quality', 'Quality Checking and Packing'), ('Checking', 'Checking and Approval')], max_length=300, verbose_name='Department')),
                ('status', models.CharField(choices=[('', 'Select'), ('yettostart', 'Yet to Start'), ('Processing', 'Processing'), ('Finish', 'Finish')], max_length=300, verbose_name='Staus')),
                ('notes', models.TextField(max_length=3000, null=True, verbose_name='Notes')),
                ('buyer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.order_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=300)),
                ('no_of_stock', models.CharField(max_length=300)),
                ('buyer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.order_detail')),
                ('stock_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stock')),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='buyers',
            field=models.ManyToManyField(through='app.Stock_Detail', to='app.Order_Detail'),
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, verbose_name='Order Id')),
                ('material_name', models.CharField(max_length=300, null=True, verbose_name='Material Name')),
                ('total_quantity', models.CharField(max_length=30, verbose_name='Total Quantity')),
                ('shipped_date', models.DateField()),
                ('delivered_date', models.DateField()),
                ('mode_of_shippment', models.CharField(max_length=300, verbose_name='Mode of Shipping')),
                ('notes', models.TextField(max_length=3000, null=True, verbose_name='Notes')),
                ('buyer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.order_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, verbose_name='Order Id')),
                ('due_date', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=200)),
                ('notes', models.TextField(max_length=3000, null=True, verbose_name='Notes')),
                ('payment_status', models.CharField(choices=[('', 'Select'), ('rised', 'Invoice Rised'), ('send', 'Email Send'), ('paid', 'Payment Received')], max_length=300, verbose_name='Payment Status')),
                ('created_date', models.DateField(default=datetime(2020, 11, 2, 5, 55, 23, 134482, tzinfo=timezone.utc))),
                ('buyer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.order_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('month', models.CharField(max_length=200)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee_detail')),
            ],
        ),
    ]
