# Generated by Django 3.1.2 on 2020-11-02 07:48

import datetime
from django.db import migrations, models
#from django.utils.timezone import utc
from datetime import datetime, timezone

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_detail',
            name='per_day',
            field=models.CharField(max_length=100, null=True, verbose_name='Per Day Salary'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_date',
            field=models.DateField(default=datetime(2020, 11, 2, 7, 48, 43, 368922, tzinfo=timezone.utc)),
        ),
    ]
