# Generated by Django 3.1.3 on 2020-12-17 09:05

import datetime
from django.db import migrations, models
#from django.utils.timezone import utc
from datetime import datetime, timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201102_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=300, verbose_name='Company Name')),
                ('job_title', models.CharField(max_length=300, verbose_name='Job Title')),
                ('description', models.CharField(max_length=300, verbose_name='Job Description')),
                ('position', models.CharField(max_length=300, verbose_name='Position')),
                ('experience', models.CharField(max_length=300, verbose_name='Experience')),
                ('area_of_work', models.CharField(choices=[('', 'Select'), ('Knitting', 'Knitting'), ('Dying', 'Dying'), ('Cutting', 'Cutting and Stitching'), ('Printing', 'Printing'), ('Ironing', 'Ironing'), ('Quality', 'Quality Checking and Packing'), ('Checking', 'Checking and Approval')], max_length=300, verbose_name='Area of Work')),
                ('salary', models.CharField(max_length=300, verbose_name='Salary')),
                ('status', models.CharField(choices=[('', 'Select'), ('Open', 'Open'), ('Closed', 'Closed')], max_length=30, null=True, verbose_name='Job Status')),
            ],
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_date',
            field=models.DateField(default=datetime(2020, 12, 17, 9, 5, 3, 701692, tzinfo=timezone.utc)),
        ),
    ]
