# Generated by Django 3.1.3 on 2020-12-17 09:16

import datetime
from django.db import migrations, models
#from django.utils.timezone import utc
from datetime import datetime, timezone

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201217_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email Id')),
                ('mobile', models.CharField(max_length=30, verbose_name='Mobile Num')),
                ('username', models.CharField(max_length=30, verbose_name='Username')),
                ('password', models.CharField(max_length=30, verbose_name='Password')),
                ('dob', models.DateField()),
                ('resume', models.FileField(null=True, upload_to='documents/', verbose_name='Bio Data')),
                ('city', models.CharField(max_length=300, verbose_name=' City')),
                ('address', models.TextField(max_length=2000, verbose_name=' Address')),
            ],
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_date',
            field=models.DateField(default=datetime(2020, 12, 17, 9, 16, 24, 478972, tzinfo=timezone.utc)),
        ),
    ]
