# Generated by Django 3.1.3 on 2020-12-17 09:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
#from django.utils.timezone import utc
from datetime import datetime, timezone

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201217_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='created_date',
            field=models.DateField(default=datetime(2020, 12, 17, 9, 50, 53, 931993, tzinfo=timezone.utc)),
        ),
        migrations.CreateModel(
            name='Job_Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applier_name', models.CharField(max_length=300, verbose_name='Job Applier Name')),
                ('status', models.CharField(blank=True, choices=[('', 'Select'), ('Shorlisted', 'Shorlisted'), ('Rejected', 'Rejected'), ('Hired', 'Hired')], max_length=300, null=True, verbose_name='Status')),
                ('interview_date', models.DateField(blank=True, null=True, verbose_name='Interview Date')),
                ('time', models.CharField(blank=True, max_length=30, null=True, verbose_name='Interview Time')),
                ('address', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Interview Conducting Place')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.job_detail')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userdetail')),
            ],
        ),
    ]
