# Generated by Django 3.1.3 on 2020-12-17 09:57

import datetime
from django.db import migrations, models
#from django.utils.timezone import utc
from datetime import datetime, timezone

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201217_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_apply',
            name='applier_name',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_date',
            field=models.DateField(default=datetime(2024, 4, 2, 17, 19, 32, 346831, tzinfo=timezone.utc)),

        ),
    ]
