# Generated by Django 3.2 on 2024-04-02 11:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
#from django.utils.timezone import utc
from datetime import datetime, timezone

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201217_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='created_date',
            field=models.DateField(default=datetime(2024, 4, 2, 11, 8, 4, 24530, tzinfo=timezone.utc)),
        ),
        migrations.AlterField(
            model_name='job_apply',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('pending', 'Pending'), ('Shorlisted', 'Shorlisted'), ('Rejected', 'Rejected'), ('Hired', 'Hired')], max_length=300, null=True, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=100)),
                ('expense_purpose', models.CharField(max_length=500)),
                ('expense_amount', models.BigIntegerField()),
                ('expense_file', models.ImageField(upload_to='Expense')),
                ('expense_date', models.DateTimeField(auto_now_add=True)),
                ('expense_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hrteam')),
            ],
        ),
    ]
