# Generated by Django 3.2 on 2024-04-02 17:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
#from django.utils.timezone import utc
from datetime import datetime, timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20240402_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='created_date',
            field=models.DateField(default=datetime(2024, 4, 2, 17, 19, 32, 346831, tzinfo=timezone.utc)),

        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_name', models.CharField(max_length=200)),
                ('meeting_platform', models.CharField(max_length=100)),
                ('meeting_place', models.CharField(max_length=200)),
                ('meeting_date', models.DateTimeField()),
                ('meeting_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee_detail')),
            ],
        ),
    ]
