# Generated by Django 3.2 on 2024-04-02 17:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
#from django.utils.timezone import utc
from datetime import datetime, timezone

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20240402_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='created_date',
            field=models.DateField(default=datetime(2024, 4, 2, 17, 19, 32, 346831, tzinfo=timezone.utc)),

        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userdetail'),
        ),
    ]
