# Generated by Django 3.2 on 2024-04-02 18:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
from datetime import datetime, timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20240402_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='created_date',
            field=models.DateField(default=datetime(2024, 4, 2, 17, 19, 32, 346831, tzinfo=timezone.utc)),

        ),
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_policy', models.CharField(max_length=200)),
                ('medical_description', models.CharField(max_length=200)),
                ('medical_amount', models.BigIntegerField()),
                ('medical_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userdetail')),
            ],
        ),
    ]
