# Generated by Django 3.2 on 2024-04-02 18:23

import datetime
from django.db import migrations, models
#from django.utils.timezone import utc
from datetime import datetime, timezone

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20240402_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=200)),
                ('stock_description', models.CharField(max_length=200)),
                ('stock_quantity', models.CharField(max_length=200)),
                ('stock_damages', models.CharField(default='No Damages', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_date',
            field=models.DateField(default=datetime(2024, 4, 2, 17, 19, 32, 346831, tzinfo=timezone.utc)),

        ),
    ]
