# Generated by Django 5.0.3 on 2024-11-09 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20240402_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 9, 6, 19, 42, 349714, tzinfo=datetime.timezone.utc)),
        ),
    ]
